WITH RECURSIVE CTE AS (
  SELECT 0 AS HOUR
  UNION
  SELECT HOUR + 1
  FROM CTE
  WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS ON HOUR = HOUR(DATETIME)
GROUP BY HOUR
ORDER BY HOUR;